
export interface Tracking {
    INT_SHIPMENTDOCUMENTID: number;
    VCH_SHIPMENTDOCUMENTSERIE: string;
    VCH_SHIPMENTDOCUMENTNUMBER: string;
    VCH_REQUESTCODE: string;
    VCH_QUOTATIONCODE: string;
    VCH_SHIPMENTNUMBER: string;
    DAT_DATECREATE: Date
}