
export interface Tracking {
    INT_SHIPMENTDOCUMENTID: number;
    VCH_SYSTEM: string;
    VHC_WAY: string;
    VHC_REGIME: string;
    VCH_SHIPMENTDOCUMENTSERIE: string;
    VCH_SHIPMENTDOCUMENTNUMBER: string;
    DAT_ARRIVALDATE: Date;
    DAT_DEPARTUREDATE: Date;
    VCH_SHIPMENTDOCUMENTSERIEMASTER: string;
    VCH_SHIPMENTDOCUMENTNUMBERMASTER: string;
    VCH_SERVICEREQUESTCODE: string;
    VCH_SHIPMENTNUMBER: string;
    VCH_ORIGIN:string;
    VCH_DESTINATION:string;
}