site_name: Documentación Customer Portal

nav:
    - Inicio: 'index.md'
    - Dashboard: 'dashboard.md'
    - Autentificación: 'login.md'
    - Seguimiento: 'tracking.md'
    - Configuraciones: 'config.md'

theme:
  name: material
  language: es
  features:
    - navigation.top
    - search.suggest
  favicon: img/favicon.ico
  logo: img/hellmann.png

extra_css:
  - css/main.css

extra_javascript:
  - js/main.js

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: Copyright &copy; 2022 - Hellmann Worldwide Logistics

extra:
  generator: false